

spring.application.name=tnal_prochum

# Telegram


telegram.bot.username=num_meeting_bot
telegram.bot.token=8967288042:AAEPtJFwiD4c0wdWl5qrqpk9xO4HHdbvN_A
telegram.admin.chatid=2113403037





spring.datasource.url=jdbc:h2:file:./data/meetingdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false






